all:
	g++ -g Init.cpp Dict.cpp Logger.cpp Query.cpp test_server.cpp Mutex.cpp Cache.cpp Thread.cpp WorkThread.cpp ThreadPool.cpp EncodingConverter.cpp Condition.cpp Socket.cpp -o server -lpthread -ljson -std=c++11 
	exec ./exec_task.sh
